// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/shortener.proto

package shortenerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenRequest) Reset() {
	*x = ShortenRequest{}
	mi := &file_api_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenRequest) ProtoMessage() {}

func (x *ShortenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenRequest.ProtoReflect.Descriptor instead.
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenResponse) Reset() {
	*x = ShortenResponse{}
	mi := &file_api_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenResponse) ProtoMessage() {}

func (x *ShortenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenResponse.ProtoReflect.Descriptor instead.
func (*ShortenResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_api_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_api_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ResolveResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsRequest) Reset() {
	*x = GetUserURLsRequest{}
	mi := &file_api_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsRequest) ProtoMessage() {}

func (x *GetUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{4}
}

type GetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURL             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_api_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserURLsResponse) GetUrls() []*UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type UserURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Short         string                 `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Deleted       bool                   `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURL) Reset() {
	*x = UserURL{}
	mi := &file_api_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURL) ProtoMessage() {}

func (x *UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURL.ProtoReflect.Descriptor instead.
func (*UserURL) Descriptor() ([]byte, []int) {
	return file_api_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *UserURL) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *UserURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UserURL) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_api_shortener_proto protoreflect.FileDescriptor

const file_api_shortener_proto_rawDesc = "" +
	"\n" +
	"\x13api/shortener.proto\x12\tshortener\"\"\n" +
	"\x0eShortenRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\".\n" +
	"\x0fShortenResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\" \n" +
	"\x0eResolveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x0fResolveResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"\x14\n" +
	"\x12GetUserURLsRequest\"=\n" +
	"\x13GetUserURLsResponse\x12&\n" +
	"\x04urls\x18\x01 \x03(\v2\x12.shortener.UserURLR\x04urls\"K\n" +
	"\aUserURL\x12\x14\n" +
	"\x05short\x18\x01 \x01(\tR\x05short\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\adeleted\x18\x03 \x01(\bR\adeleted2\xe4\x01\n" +
	"\x10ShortenerService\x12@\n" +
	"\aShorten\x12\x19.shortener.ShortenRequest\x1a\x1a.shortener.ShortenResponse\x12@\n" +
	"\aResolve\x12\x19.shortener.ResolveRequest\x1a\x1a.shortener.ResolveResponse\x12L\n" +
	"\vGetUserURLs\x12\x1d.shortener.GetUserURLsRequest\x1a\x1e.shortener.GetUserURLsResponseB.Z,github.com/Vaha95/golang_pet/api/shortenerpbb\x06proto3"

var (
	file_api_shortener_proto_rawDescOnce sync.Once
	file_api_shortener_proto_rawDescData []byte
)

func file_api_shortener_proto_rawDescGZIP() []byte {
	file_api_shortener_proto_rawDescOnce.Do(func() {
		file_api_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_shortener_proto_rawDesc), len(file_api_shortener_proto_rawDesc)))
	})
	return file_api_shortener_proto_rawDescData
}

var file_api_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_shortener_proto_goTypes = []any{
	(*ShortenRequest)(nil),      // 0: shortener.ShortenRequest
	(*ShortenResponse)(nil),     // 1: shortener.ShortenResponse
	(*ResolveRequest)(nil),      // 2: shortener.ResolveRequest
	(*ResolveResponse)(nil),     // 3: shortener.ResolveResponse
	(*GetUserURLsRequest)(nil),  // 4: shortener.GetUserURLsRequest
	(*GetUserURLsResponse)(nil), // 5: shortener.GetUserURLsResponse
	(*UserURL)(nil),             // 6: shortener.UserURL
}
var file_api_shortener_proto_depIdxs = []int32{
	6, // 0: shortener.GetUserURLsResponse.urls:type_name -> shortener.UserURL
	0, // 1: shortener.ShortenerService.Shorten:input_type -> shortener.ShortenRequest
	2, // 2: shortener.ShortenerService.Resolve:input_type -> shortener.ResolveRequest
	4, // 3: shortener.ShortenerService.GetUserURLs:input_type -> shortener.GetUserURLsRequest
	1, // 4: shortener.ShortenerService.Shorten:output_type -> shortener.ShortenResponse
	3, // 5: shortener.ShortenerService.Resolve:output_type -> shortener.ResolveResponse
	5, // 6: shortener.ShortenerService.GetUserURLs:output_type -> shortener.GetUserURLsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_shortener_proto_init() }
func file_api_shortener_proto_init() {
	if File_api_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shortener_proto_rawDesc), len(file_api_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shortener_proto_goTypes,
		DependencyIndexes: file_api_shortener_proto_depIdxs,
		MessageInfos:      file_api_shortener_proto_msgTypes,
	}.Build()
	File_api_shortener_proto = out.File
	file_api_shortener_proto_goTypes = nil
	file_api_shortener_proto_depIdxs = nil
}
